# Generated by Django 3.2.14 on 2022-07-07 13:49

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('color', models.TextField(max_length=20, verbose_name='Цвет')),
            ],
        ),
        migrations.CreateModel(
            name='Writing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=500, verbose_name='Запись')),
                ('length', models.IntegerField()),
                ('time_create', models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 7, 13, 49, 4, 401309, tzinfo=utc), null=True)),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.tag')),
            ],
        ),
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=20, verbose_name='Имя')),
                ('age', models.IntegerField()),
                ('is_writing', models.BooleanField(default=False)),
                ('birthday', models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 7, 13, 49, 4, 401309, tzinfo=utc), null=True)),
                ('writing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.writing')),
            ],
        ),
    ]
