# Generated by Django 3.2.14 on 2022-07-07 13:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='birthday',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 7, 13, 54, 28, 603053, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='writing',
            name='time_create',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 7, 7, 13, 54, 28, 603053, tzinfo=utc), null=True),
        ),
    ]
