# Generated by Django 3.2.12 on 2022-09-06 18:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_auto_20220707_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='birthday',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 9, 6, 18, 6, 31, 626473, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='writing',
            name='time_create',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 9, 6, 18, 6, 31, 634483, tzinfo=utc), null=True),
        ),
    ]
